### PR TITLE
🌐 feat: Portuguese Translation

### PR DESCRIPTION
**Pull request by luisfelipesdn12**
I've started the translation to pt-BR.

### CODE REVIEW

**Comment by casperiv0** [comment]
@luisfelipesdn12 make sure to pull down the latest changes from `main`. There's some things that were deleted and don't need to be translated anymore

**Comment by luisfelipesdn12** [comment]
Translation completed :)

**Comment by Xaliks** [comment]
:+1:

**Review by casperiv0 — COMMENTED** [review]
Thanks a lot 🔥!

**Pull request merged**
