### PR TITLE
YouTube Fake Comment

### PR DESCRIPTION
**Pull request by LakhindarPal**
create YouTube Fake Comment. just use the Command and write your comment

### CODE REVIEW

**Comment by LackyPal** [comment]
If I click on the link, i get the image. But the image is not loaded on the embed. I have tried many times. I don't know why. Besides everything is working

**Comment by casperiv0** [comment]
Yea, I'm getting the same issue. I think It's something to do with Discord blocking the URL. Weird.

**Comment by casperiv0** [comment]
Will be closing this pull request since the URL doesn't embed the image.

**Comment by casperiv0** [comment]
This issue seemed to be resolved so decided to add it back.

**Pull request closed without merging**
