### PR TITLE
Bengali translation

### PR DESCRIPTION
**Pull request by LackyPal**

### CODE REVIEW

**Comment by LackyPal** [comment]
I'm work on on Bengali translation, I'll create a fresh new pull request once done,

**Comment by casperiv0** [comment]
@L0SER8228 any status on this PR?

**Comment by LackyPal** [comment]
Sorry, but my exams are coming soon🥺

**Comment by casperiv0** [comment]
> Sorry, but my exams are coming soon🥺

No worries!

**Comment by casperiv0** [comment]
@L0SER8228 Any status on this PR :)?

**Comment by LackyPal** [comment]
😅 sorry i forget about it
Ok I'll done it soon

**Comment by casperiv0** [comment]
Will be closing this since it's been inactive for a long time. Feel free to re-open when you can finish this :)

**Pull request closed without merging**
