### PR TITLE
Added Music improvements and personal todo list

### PR DESCRIPTION
**Pull request by johnnyhliang**
It would also be great to add a better documentation for dashboard unless its not finished. Instead of creating an issue, I might as well state it here; `{"code": 50035, "errors": {"redirect_uri": {"_errors": [{"code": "URL_TYPE_INVALID_URL", "message": "Not a well formed URL."}]}}, "message": "Invalid Form Body"}`

^^^^^^
I get this when trying to access the dashboard when redirected to https://discordapp.com/api/v8/oauth2/authorize

I suspect it to be an issue with the jwt token, the credentials or the "Your Url" before the callback. 
If any of the contributers or CasperTheGhost reads this, it would be greatly appreciated! 

**Improvements**

I have replaced the music system to be better modified. The asthetics of the embeds can easily be modified and maybe use the base embed module I saw when reviewing the original code. If anyone cares to improve on this commit feel free to do so!

Next commit I will likely work on that as well as the items stated in the todo list.

### CODE REVIEW

**Comment by casperiv0** [comment]
Before you do anything else, can you please re-add all the commands you deleted and update your local branch because it is very out of date.

**Comment by casperiv0** [comment]
Oh and please don’t change other code not needed for this pr

**Comment by johnnyhliang** [comment]
Ok tmw I will just redo the music system, not mess with anything else. I decided to do some extra things like delete all nsfw for my server and retheme for a self hosted bot on a tiny server. I hope nothing I did causes any anger or confusion just to make it clear!

**Comment by johnnyhliang** [comment]
Btw I cloned the bot like yesterday so Im not sure what could be causing things to be out of date besides me modifying a lot of files

**Comment by johnnyhliang** [comment]
If there are any other inquiries then my discord is hurb#7444

**Comment by casperiv0** [comment]
Ah, you added ytdl-discord but we're using discord-player and will be sticking to that. You'll need to add back the nsfw commands to this PR and the config.example you'll need to revert aswell

**Comment by casperiv0** [comment]
> 
> 
> Btw I cloned the bot like yesterday so Im not sure what could be causing things to be out of date besides me modifying a lot of files

Do you mind re-cloning this repo with everything updated since some of the code was changed yesterday

**Comment by johnnyhliang** [comment]
> > Btw I cloned the bot like yesterday so Im not sure what could be causing things to be out of date besides me modifying a lot of files
> 
> Do you mind re-cloning this repo with everything updated since some of the code was changed yesterday

In that case I don't really have that many improvements to make but I will work on it after Christmas. Its also 1 am so I kinda gotta sleep.

**Pull request closed without merging**
