### PR TITLE
updated kick, ban, mute, addrole, removerole command

### PR DESCRIPTION
**Pull request by iamgobinda**
i have just updated these commands. Add some aliases. Error checking on these commands are now more specific and clear.

### CODE REVIEW

**Comment by casperiv0** [comment]
Are you participating in hacktoberfest? Please let me know so I can add the needed labels.

**Comment by LackyPal** [comment]
I'm also participating, 😊

**Comment by iamgobinda** [comment]
Please add hactoberfest label on my previous pull request too

**Comment by casperiv0** [comment]
Done. :) Ill merge this PR when home later today.

**Review by casperiv0 — APPROVED** [review]
Looks good.

**Pull request merged**
