### PR TITLE
chore: remove redundant logic and replace with `Guild#nameAcronym` 

### PR DESCRIPTION
**Pull request by yehorovye**

### CODE REVIEW

**Review by casperiv0 — CHANGES_REQUESTED** [review]
Please fix linting errors, `npm run format`

**Comment by yehorovye** [comment]
ok, gimme a sec

**Review by casperiv0 — APPROVED** [review]
Looks like it’s still failing, but will fix locally. Will also merge later today

**Comment by yehorovye** [comment]
Oh i see, anyways no problem ^^

**Pull request merged**
